version: '3.4'

services:
  db:
    image: mysql:5.7.22
    command: mysql --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile    
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_api
    ports:
      - "3308:3306"
    networks: 
      - api-network

  dotnet-core-api-rest:
    image: dotnet-core-api
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:80"
    networks: 
      - api-network

networks:
  api-network: 
    driver: bridge
   