


CREATE TABLE `persons` (
    `Id` int(10) UNSIGNED NULL DEFAULT NULL,
    `Name` VARCHAR(50) NULL DEFAULT NULL,
    `LastName` VARCHAR(50) NULL DEFAULT NULL,
    `Country` VARCHAR(50) NULL DEFAULT NULL,
    `City` VARCHAR(50) NULL DEFAULT NULL,
    `Address` VARCHAR(50) NULL DEFAULT NULL,
    `Gender` VARCHAR(50) NULL DEFAULT NULL,
    `Age`  INTEGER NULL DEFAULT NULL,
    `Birthday` DATE NULL DEFAULT NULL,
    `Email` VARCHAR(50) NULL DEFAULT NULL,
    `CreateOn` DATETIME  DEFAULT now()
)
ENGINE=InnoDB
;

